//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubiquity.NET.Versioning.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubiquity.NET.Versioning.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphaNumericIdentifier is missing a non-digit character.
        /// </summary>
        internal static string alphanumericIdentifier_is_missing_a_non_digit_character {
            get {
                return ResourceManager.GetString("alphanumericIdentifier_is_missing_a_non_digit_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSemVer-CI ZeroTimed versions cannot use a pre-release as the base build.
        /// </summary>
        internal static string csemver_ci_zerotimed_versions_cannot_use_a_pre_release_as_the_base_build {
            get {
                return ResourceManager.GetString("csemver_ci_zerotimed_versions_cannot_use_a_pre_release_as_the_base_build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSemVer pre-release supports no more than 3 components. {0}.
        /// </summary>
        internal static string CSemVer_pre_release_supports_no_more_than_3_components_0 {
            get {
                return ResourceManager.GetString("CSemVer_pre_release_supports_no more_than_3_components_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains invalid value &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string exp_0_contains_invalid_value_1_2 {
            get {
                return ResourceManager.GetString("exp_0_contains_invalid_value_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format string &apos;{0}&apos;.
        /// </summary>
        internal static string invalid_format_string_0 {
            get {
                return ResourceManager.GetString("invalid_format_string_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODD File versions are reserved for CI versions; use CSemVerCI.From() to convert those.
        /// </summary>
        internal static string odd_file_versions_are_reserved_for_CI {
            get {
                return ResourceManager.GetString("odd_file_versions_are_reserved_for_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be in range {1}. {2}.
        /// </summary>
        internal static string value_0_must_be_in_range_1_2 {
            get {
                return ResourceManager.GetString("value_0_must_be_in_range_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null or whitespace.
        /// </summary>
        internal static string value_is_null_or_whitespace {
            get {
                return ResourceManager.GetString("value_is_null_or_whitespace", resourceCulture);
            }
        }
    }
}
